// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4VTJsVXbypyn1B4RWMdBN5PUjjXQobko',
    appId: '1:855576067354:web:76436292b4d708b7a540a3',
    messagingSenderId: '855576067354',
    projectId: 'banking-lessons-app',
    authDomain: 'banking-lessons-app.firebaseapp.com',
    storageBucket: 'banking-lessons-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFU9NQYvKaXmJrW5KON5w7qQR6iwVx0jU',
    appId: '1:855576067354:android:158b97e162d40ff3a540a3',
    messagingSenderId: '855576067354',
    projectId: 'banking-lessons-app',
    storageBucket: 'banking-lessons-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpXqM-BhQmUaWjV9iJ9Kc12dpoJTTGC9c',
    appId: '1:855576067354:ios:5a90d850f3ce9ddfa540a3',
    messagingSenderId: '855576067354',
    projectId: 'banking-lessons-app',
    storageBucket: 'banking-lessons-app.appspot.com',
    iosClientId:
        '855576067354-l02ch5adj75njndgscaobir716jpb424.apps.googleusercontent.com',
    iosBundleId: 'com.ht369.app',
  );
}
